language: node_js

os:
  # - windows
  - linux
  - osx

node_js:
  - "11"
  - "10"
  - "9"
  - "8"

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-4.0.5.tgz
  - tar -zxvf mongodb-linux-x86_64-4.0.5.tgz
  - mkdir -p ./data/db/27017
  - ./mongodb-linux-x86_64-4.0.5/bin/mongod --fork --dbpath ./data/db/27017 --syslog --port 27017
  - sleep 2

script:
  - npm run codecov

cache:
  directories:
    - "node_modules"

notifications:
  email:
    on_success: never
    on_failure: always
